### ISSUE TITLE
The unit test named "Issue96Test" randomly failed

### ISSUE THREAD

**Issue by Rizen59** [dooApp/FXForm2#123]
Test launched under Intellij IDEA 2016.1.2 - maven 3.2.5 - jdk 8u92

**Comment by amischler** [comment]
Due to Platform.runLater call in PropertyEditorController which triggers a validation in the JavaFX Thread which may be modifying the contraint list while the test is checking it.

However, in the current test no call to validate should be made in the view change listener since the change does not modify the model value (the view is being initialized). We should check this before call the validator.
