### ISSUE TITLE
The @NonVisual annotation does not work in a ListProperty Bean

### ISSUE THREAD

**Issue by christophe-dooapp** [dooApp/FXForm2#52]

**Comment by garzy** [comment]
I Have this issue in 8.3.0-SNAPSHOT, fix this please

**Comment by garzy** [comment]
Sorry I don't understans it's mi case.

In the ListPropertyForm example I change this:

` public StringProperty firstName = new SimpleStringProperty();
  public StringProperty lastName = new SimpleStringProperty();
 @NonVisual
   public ObjectProperty<Movies> favoriteMovie = new SimpleObjectProperty<>();`

Because I want that favoriteMovie doesn't show in the table inside form.

This behaviour, doesn't works.
